#if !canImport(ObjectiveC)
import XCTest

extension XCTestCaseExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestCaseExtensionTests = [
        ("testExpect", testExpect),
        ("testExpectWillFulfill", testExpectWillFulfill),
        ("testExpectWillNotFulfill", testExpectWillNotFulfill),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XCTestCaseExtensionTests.__allTests__XCTestCaseExtensionTests),
    ]
}
#endif
