#if !canImport(ObjectiveC)
import XCTest

extension XCTestCaseAssertWrappersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestCaseAssertWrappersTests = [
        ("testBoolean", testBoolean),
        ("testEquality", testEquality),
        ("testNil", testNil),
        ("testThrows", testThrows),
    ]
}

extension XCTestCaseExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestCaseExtensionTests = [
        ("testExpect", testExpect),
        ("testExpectWillFulfill", testExpectWillFulfill),
        ("testExpectWillNotFulfill", testExpectWillNotFulfill),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XCTestCaseAssertWrappersTests.__allTests__XCTestCaseAssertWrappersTests),
        testCase(XCTestCaseExtensionTests.__allTests__XCTestCaseExtensionTests),
    ]
}
#endif
