#if !canImport(ObjectiveC)
import XCTest

extension ConstructorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConstructorTests = [
        ("testObjectWillCompile", testObjectWillCompile),
    ]
}

extension KSSTextViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KSSTextViewTests = [
        ("testConstruction", testConstruction),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConstructorTests.__allTests__ConstructorTests),
        testCase(KSSTextViewTests.__allTests__KSSTextViewTests),
    ]
}
#endif
