#if !canImport(ObjectiveC)
import XCTest

extension NSApplicationExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NSApplicationExtensionTests = [
        ("testMetadata", testMetadata),
    ]
}

extension NSImageExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NSImageExtensionTests = [
        ("testInitFromInputStream", testInitFromInputStream),
        ("testInverted", testInverted),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NSApplicationExtensionTests.__allTests__NSApplicationExtensionTests),
        testCase(NSImageExtensionTests.__allTests__NSImageExtensionTests),
    ]
}
#endif
